version: '3.9'
services:
  server:
    image: docker.tgrep.nl/docker/rust-dev:1.73
    volumes:
      - ./server:/app/server
      - target:/app/server/target
      - ./core:/app/core
      - ./signal-detector:/app/signal-detector
      - registry:/usr/local/cargo/registry
      - git:/usr/local/cargo/git
    command: [ "cargo", "watch", "-x", "run", "--poll" ]
    working_dir: /app/server
    environment:
      MQTT: "mqtt:1883"
      LOG: debug
      RUST_BACKTRACE: 1
    networks: [default]
    restart: unless-stopped
    tty: true

  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports: ["1883:1883", "9001:9001"]
    networks: [default]

networks:
  default: ~

volumes:
  target: ~
  registry: ~
  git: ~
